# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/cuxfilter/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/cuxfilter/labels

Python:
 - 'python/**'
 - 'notebooks/**'

cpp:
 - 'cpp/**'

CMake:
 - '**/CMakeLists.txt'
 - '**/cmake/**'

gpuCI:
   - 'ci/**'

conda:
   - 'conda/**'
